# Generated by Django 4.2.7 on 2023-11-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeuser",
            name="subscription_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
