version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dealscan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  dealscan:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - SECRET_KEY=secret
      - ENVIRONMENT=dev
      - DATABASE_URL=postgres://postgres:postgres@db/dealscan
      - REDIS_URL=redis://redis/0
    depends_on:
      - db
      - redis
      - migrations
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10

  sync:
    build:
      dockerfile: Dockerfile
    container_name: sync
    restart: no
    command: python manage.py djstripe_sync_models
    env_file:
      - .env
    depends_on:
      dealscan:
        condition: service_started

  refresher:
    build:
      dockerfile: Dockerfile
    command: ./crawler/jobs.sh
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  migrations:
    build:
      dockerfile: Dockerfile
    container_name: migrations
    restart: no
    command: python manage.py migrate --noinput
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to dealscan:8000/payments/webhook/ --skip-verify
    depends_on:
      - dealscan
    env_file:
      - .env
    environment:
      - STRIPE_API_KEY=${STRIPE_TEST_SECRET_KEY}