version: '3.3'

services:
  dealscan-redis:
    image: redis:latest
    container_name: dealscan-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dealscan-db:
    image: postgres:latest
    container_name: dealscan-db
    ports:
      - "5432:5432"
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dealscan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  dealscan:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    container_name: dealscan
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - SECRET_KEY=secret
      - ENVIRONMENT=dev
      - DATABASE_URL=postgres://postgres:postgres@dealscan-db/dealscan
      - REDIS_URL=redis://dealscan-redis/0
    depends_on:
      - dealscan-db
      - dealscan-redis
      - dealscan-migrations
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10

  dealscan-sync:
    build:
      dockerfile: Dockerfile
    container_name: dealscan-sync
    restart: no
    command: python manage.py djstripe_sync_models
    env_file:
      - .env
    depends_on:
      dealscan:
        condition: service_started

  dealscan-migrations:
    build:
      dockerfile: Dockerfile
    container_name: dealscan-migrations
    restart: no
    command: python manage.py migrate --noinput
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      dealscan-db:
        condition: service_healthy

  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to dealscan:8000/payments/webhook/ --skip-verify
    depends_on:
      - dealscan
    env_file:
      - .env
    environment:
      - STRIPE_API_KEY=${STRIPE_TEST_SECRET_KEY}

  # dealscan-celery:
  #   build:
  #     dockerfile: Dockerfile
  #   image: dealscan-celery:latest
  #   container_name: dealscan-celery
  #   command: poetry run celery -A dealscan worker -Q default -n dealscan.%%h --loglevel=INFO --max-memory-per-child=512000 --concurrency=1
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     dealscan:
  #       condition: service_healthy
  #     dealscan-redis:
  #       condition: service_healthy

  # dealscan-celery-beat:
  #     build:
  #       dockerfile: Dockerfile
  #     image: dealscan-celery-beat:latest
  #     container_name: dealscan-celery-beat
  #     command: poetry run celery -A dealscan beat -S redbeat.RedBeatScheduler --loglevel=DEBUG --pidfile /tmp/dealscan-celerybeat.pid
  #     env_file:
  #     - .env
  #     volumes:
  #       - .:/usr/src/app
  #     depends_on:
  #       - dealscan
  #       - dealscan-celery
  #       - dealscan-db
  #       - dealscan-redis

  # dealscan-celery-flower:
  #     build:
  #       dockerfile: Dockerfile
  #     container_name: dealscan-celery-flower
  #     command: poetry run celery -A dealscan flower --loglevel=INFO --port=9090 --broker=redis://dealscan-redis:6379/0 --basic_auth=dealscan:dealscan
  #     env_file:
  #     - .env
  #     ports:
  #       - "127.0.0.1:9090:9090"
  #     restart: unless-stopped
  #     volumes:
  #       - .:/usr/src/app
  #     depends_on:
  #       - dealscan
  #       - dealscan-celery
  #       - dealscan-redis