version: '3.3'

services:
  dealscan:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:8000 dealscan.wsgi:application
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - ENVIRONMENT=prod
      - DATABASE_URL=postgres://postgres:postgres@db/dealscan
      - REDIS_URL=redis://redis/0
    depends_on:
      - db
      - redis
      - migrations
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}\n' --output /dev/null http://127.0.0.1:8000/"
      start_period: 60s
      interval: 60s
      timeout: 10s
      retries: 10