TRANSMISSION_CHOICES_MAP = {
    "Automatyczna": "automatic",
    "Manualna": "manual",
}
FUEL_CHOICES_MAP = {
    "Benzyna": "petrol",
    "Diesel": "diesel",
    "Benzyna+LPG": "lpg",
    "Benzyna+CNG": "cng",
    "Diesel": "diesel",
    "Elektryczny": "electric",
    "Hybrydowy": "hybrid",
}
BODY_CHOICES_MAP = {
    "Minivan": "minivan",
    "Sedan": "sedan",
    "SUV": "suv",
    "Kombi": "combi",
    "Kompakt": "compact",
    "Coupe": "coupe",
    "Kabriolet": "cabrio",
}
COLOR_CHOICES_MAP = {
    "Beżowy": "beige",
    "Biały": "white",
    "Błękitny": "sky-blue",
    "Kasztanowy": "maroon",
    "Brązowy": "brown",
    "Czarny": "black",
    "Czerwony": "red",
    "Fioletowy": "purple",
    "Granatowy": "navy-blue",
    "Niebieski": "blue",
    "Pomarańczowy": "orange",
    "Srebrny": "silver",
    "Szary": "gray",
    "Zielony": "green",
    "Złoty": "gold",
    "Żółty": "yellow",
}
FINISH_CHOICES_MAP = {
    "Matowy": "matte",
    "Metalik": "metallic",
    "Perłowy": "pearl",
}
ORIGIN_COUNTRIES_MAP = {
    "Austria": "AT",
    "Belgia": "BE",
    "Białoruś": "BY",
    "Bułgaria": "BG",
    "Chorwacja": "HR",
    "Czechy": "CZ",
    "Dania": "DK",
    "Estonia": "EE",
    "Finlandia": "FI",
    "Francja": "FR",
    "Grecja": "GR",
    "Hiszpania": "ES",
    "Holandia": "NL",
    "Irlandia": "IE",
    "Islandia": "IS",
    "Japonia": "JP",
    "Kanada": "CA",
    "Korea": "KR",
    "Liechtenstein": "LI",
    "Litwa": "LT",
    "Luksemburg": "LU",
    "Łotwa": "LV",
    "Monako": "MC",
    "Niemcy": "DE",
    "Norwegia": "NO",
    "Polska": "PL",
    "Rosja": "RU",
    "Rumunia": "RO",
    "Słowacja": "SK",
    "Słowenia": "SI",
    "Stany Zjednoczone": "US",
    "Szwajcaria": "CH",
    "Szwecja": "SE",
    "Turcja": "TR",
    "Ukraina": "UA",
    "Węgry": "HU",
    "Wielka Brytania": "GB",
    "Włochy": "IT",
}
MONTH_TRANSLATION_MAP = {
    "styczeń": 1,
    "luty": 2,
    "marzec": 3,
    "kwiecień": 4,
    "maj": 5,
    "czerwiec": 6,
    "lipiec": 7,
    "sierpień": 8,
    "wrzesień": 9,
    "październik": 10,
    "listopad": 11,
    "grudzień": 12,
}
