# Generated by Django 4.2.7 on 2023-11-19 01:19

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offermetadata",
            name="from_authorized_dealer",
        ),
        migrations.RemoveField(
            model_name="offermetadata",
            name="has_registration_number",
        ),
        migrations.RemoveField(
            model_name="offermetadata",
            name="radio",
        ),
        migrations.AddField(
            model_name="offer",
            name="image_url",
            field=models.URLField(
                blank=True, null=True, unique=True, verbose_name="image_url"
            ),
        ),
        migrations.AlterField(
            model_name="historicalsource",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="offer",
            name="damaged",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="is vehicle damaged"
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="drive",
            field=models.CharField(blank=True, null=True, verbose_name="drive"),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="color_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("matte", "Matte"),
                    ("metallic", "Metallic"),
                    ("pearl", "Pearl"),
                ],
                null=True,
                verbose_name="vehicle color type",
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="first_owner",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="first owner"
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="in_town_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="in town fuel consumption",
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="left_steering_wheel",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="does vehicle have steering wheel on the left side",
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="never_damaged",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="have vehicle been ever damaged"
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="origin_country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True, verbose_name="origin country"
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="out_of_town_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="out of town fuel consumption",
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="seats_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="seats count"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
    ]
