# Generated by Django 4.2.7 on 2023-11-19 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_remove_offermetadata_from_authorized_dealer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermetadata",
            name="registration_number",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="registration number"
            ),
        ),
    ]
