# Generated by Django 4.2.7 on 2023-11-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_offermetadata_registration_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offermetadata",
            name="features",
            field=models.JSONField(blank=True, null=True, verbose_name="car features"),
        ),
    ]
