# Generated by Django 4.2.7 on 2023-11-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_alter_carmake_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
