# Generated by Django 4.2.7 on 2023-11-18 01:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0005_alter_carmodel_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="carmodel",
            name="unique_car_model_for_make",
        ),
        migrations.AlterUniqueTogether(
            name="carmodel",
            unique_together={("make", "name")},
        ),
    ]
