# Generated by Django 4.2.7 on 2023-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_alter_offer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="displacement",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="engine displacement"
            ),
        ),
        migrations.AlterField(
            model_name="offermetadata",
            name="doors_count",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="doors count"
            ),
        ),
    ]
