# Generated by Django 4.2.7 on 2023-11-18 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_remove_carmodel_unique_car_model_for_make_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsource",
            name="etag",
        ),
        migrations.RemoveField(
            model_name="historicalsource",
            name="status_code",
        ),
        migrations.RemoveField(
            model_name="source",
            name="etag",
        ),
        migrations.RemoveField(
            model_name="source",
            name="status_code",
        ),
    ]
