# Generated by Django 4.2.7 on 2023-12-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0007_alter_offer_displacement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="image_url",
            field=models.URLField(
                blank=True,
                max_length=2048,
                null=True,
                unique=True,
                verbose_name="image_url",
            ),
        ),
    ]
