# Generated by Django 4.2.7 on 2023-12-03 22:30

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=256, verbose_name="label")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "default_answers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=256),
                        size=None,
                    ),
                ),
                (
                    "allow_custom_answer",
                    models.BooleanField(default=True, max_length=512),
                ),
                ("use_ratings", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PollAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("answer", models.CharField()),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answer",
                        to="polls.poll",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="poll",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
