# Generated by Django 4.2.7 on 2023-12-03 23:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pollanswer",
            unique_together={("user", "poll")},
        ),
    ]
